config/routes.rb
Rails.application.routes.draw do

  root 'sports#index'

  get 'logout' => 'application#logout'
  get 'login' => 'application#login'
  get 'search' => 'players#search'

  resources :sports do
    resources :clubs do
      resources :players
    end
  end

end

app/models/club.rb
class Club < ActiveRecord::Base
  has_many :players, dependent: :destroy
  belongs_to :sport
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :club
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :clubs, dependent: :destroy
  validates :title, presence: true, length: {minimum: 4}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate, :only => [:login]

  def logout
    host = env['HTTP_HOST']
    protocol = root_url.split(host)
    logout_url = "#{request.protocol}guest:password@#{env['HTTP_HOST']}"
    redirect_to logout_url
  end

  def login
    redirect_to :back and return
  end

  protected
    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == USER_ID && password == PASSWORD
      end
    end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController

  before_filter :authenticate, :except => [:index, :show]

  def index
    @sport = Sport.find(params[:sport_id])
  end

  def show
    @club = Club.find(params[:id])
  end

  def new
    @sport = Sport.find(params[:sport_id])
    @club = Club.new(sport: @sport)
  end

  def create
    @sport = Sport.find(params[:sport_id])
    @club = @sport.clubs.new(club_params)
    if @club.save
      redirect_to sport_club_path(@club.sport_id, @club)
    else
      render 'new'
    end
  end

  def edit
    @club = Club.find(params[:id])
    @sport = @club.sport
  end

  def update
    @club = Club.find(params[:id])

    if @club.update(club_params)
      redirect_to sport_club_path(@club.sport_id, @club)
    else
      render 'edit'
    end
  end

  def destroy
    @club = Club.find(params[:id])
    @sport = @club.sport

    @club.destroy
    redirect_to sport_clubs_path(@sport)
  end


  private

  def club_params
    params.require(:club).permit(:name, :image_link, :country, :established, :description)
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_filter :authenticate, :except => [:index, :show, :search]

  def index
    @club = Club.find(params[:club_id])
  end

  def show
    @player = Player.find(params[:id])
  end

  def new
    @sport = Sport.find(params[:sport_id])
    @club = Club.find(params[:club_id])
    @player = Player.new(club: @club)
  end

  def create
    @sport = Sport.find(params[:sport_id])
    @club = Club.find(params[:club_id])
    @player = @club.players.new(player_params)
    if @player.save
      redirect_to sport_club_player_path(@sport.id, @club.id, @player)
    else
      render 'new'
    end
  end

  def edit
    @player = Player.find(params[:id])
    @club = @player.club
    @sport = @club.sport
  end

  def update
    @player = Player.find(params[:id])
    @club = @player.club
    @sport = @club.sport
    if @player.update(player_params)
      redirect_to sport_club_player_path(@sport.id, @club.id, @player)
    else
      render 'edit'
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @club = @player.club
    @sport = @club.sport

    @player.destroy
    redirect_to sport_club_players_path(@sport, @club)
  end

  def search
    @query = params[:query]
    @results = Player.where("name LIKE :query", query: "%#{@query}%")
  end

  private

  def player_params
    params.require(:player).permit(:name, :image_link, :country, :position, :description)
  end

end

app/controllers/sports_controller.rb
class SportsController < ApplicationController

  before_filter :authenticate, :except => [:index, :show]

  def new
    @sport = Sport.new
  end

  def create
    @sport = Sport.new(sport_params)

    if @sport.save
      redirect_to @sport
    else
      render "new"
    end
  end

  def show
    @sport = Sport.find(params[:id])
  end

  def index
    @sports = Sport.all
  end

  def edit
    @sport = Sport.find(params[:id])
  end

  def update
    @sport = Sport.find(params[:id])

    if @sport.update(sport_params)
      redirect_to @sport
    else
      render "edit"
    end
  end

  def destroy
    @sport = Sport.find(params[:id])

    @sport.destroy
    redirect_to sports_path
  end

  private

  def sport_params
    params.require(:sport).permit(:title, :image_link, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
   not request.authorization.nil?
  end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/clubs/_form.html.haml
.form-wrapper{style: "width: 100%"}
  = form_for [@sport, @club] do |f|
    - if @club.errors.any?
      .error_msg
        %h3 #{pluralize(@club.errors.count, 'errors')} errors occurred.
        %ul
          - @club.errors.full_messages.each do |msg|
            %li #{msg}
    .row
      .form-group
        = f.text_field :name, placeholder: 'Club\'s Name', class: 'input-lg form-control'
    .row
      .col-lg-6.form-group
        = f.text_field :country, placeholder: 'Country', class: 'input-lg form-control'
      .col-lg-6.form-group
        = f.text_field :established, placeholder: 'Established Year', class: 'input-lg form-control'
    .row
      .form-group.text-center
        = f.text_field :image_link, class: 'form-control', placeholder: "Image Link"
    .row
      .form-group
        = f.label :description
        = f.text_area :description, class: 'form-control', rows: 3
    .row
      .form-group.text-center
        = f.button :submit, class: 'btn-success'


/ name
/ image_link
/ country
/ established
/ description

app/views/clubs/index.html.haml
.sports-wrapper.row
  %h1 #{@sport.title} Clubs

  %p
    = link_to "New #{@sport.title} Club", new_sport_club_path
  -@sport.clubs.each do |club|
    .sport
      .sport-head
        .name #{club.name}
      .image.center-block
        = link_to image_tag(club.image_link, style: "max-width: 640px"), sport_club_players_path(@sport.id, club), class: 'img-responsive'
      %p.caption #{club.country} (#{club.established})
      %p.caption #{club.description}
      .text-center.edit-links
        = link_to "show", sport_club_path(@sport.id, club)
        |
        = link_to "edit", edit_sport_club_path(@sport.id, club)
        |
        = link_to "delete", sport_club_path(@sport.id, club), method: :delete, data: {confirm: "Are you sure?"}


/ name
/ image_link
/ country
/ established
/ description

app/views/clubs/new.html.haml
.sports-wrapper.row
  %h1
    New Club

  = render 'form'

  %p
    = link_to "Back", sport_clubs_path

app/views/clubs/show.html.haml
.sports-wrapper.row
  %p
    %strong Club:
    ="#{@club.name}"
  %p
    %strong Country:
    ="#{@club.country}"
  %p
    %strong Established:
    ="#{@club.established}"

  %img{ src: "#{@club.image_link}", title: @club.description, style: "max-width: 640px" }

  %p.caption
    ="#{@club.description}"


  .text-center.edit-links
    = link_to "Back", sport_clubs_path(@club.sport)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title PlayerGallery
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .navbar-container
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle Navigation
            %span.icon-bar
            %span.icon-bar
          .navbar-brand= link_to "Player Gallery", root_path
        .collapse.navbar-collapse#bs-navbar-collapse-1
          %ul.nav.navbar-nav.navbar-right
            - if logged_in?
              %li= link_to 'Logout', url_for(action: 'logout', controller: 'application')
            - else
              %li
                = link_to "Login", url_for(action: 'login', controller: 'application')


          %form.navbar-form.navbar-right{:role => "search", method: 'get', action: "/search"}
            .form-group
              .input-group
                %input.form-control{:placeholder => "#{@query || 'Search for Player...'}", id: 'query', name: 'query', :type => "text"}
                  %span.input-group-btn

                    %button.btn.btn-default{"aria-label" => "Left Align", :type => "button"}
                      %span.glyphicon.glyphicon-search{"aria-hidden" => "true"}

          %ul.nav.navbar-nav.navbar-right
            %li
              %a{:href => "/"}
                %span.glyphicon.glyphicon-home
    = yield

app/views/players/_form.html.haml
.form-wrapper{style: "width: 100%"}
  = form_for [@sport, @club, @player] do |f|
    - if @player.errors.any?
      .error_msg
        %h3 #{pluralize(@player.errors.count, 'errors')} errors occurred.
        %ul
          - @player.errors.full_messages.each do |msg|
            %li #{msg}
    .row
      .form-group
        = f.text_field :name, placeholder: 'Player\'s Name', class: 'input-lg form-control'
    .row
      .col-lg-6.form-group
        = f.text_field :country, placeholder: 'Country', class: 'input-lg form-control'
      .col-lg-6.form-group
        = f.text_field :position, placeholder: 'Position', class: 'input-lg form-control'
    .row
      .form-group.text-center
        = f.text_field :image_link, class: 'form-control', placeholder: "Image Link"
    .row
      .form-group
        = f.label :description
        = f.text_area :description, class: 'form-control', rows: 3
    .row
      .form-group.text-center
        = f.button :submit, class: 'btn-success'


/ name
/ image_link
/ country
/ position
/ description

app/views/players/edit.html.haml
.sports-wrapper.row
  %h1
    Edit Sports

  = render 'form'

  %p
    = link_to "Back", sport_clubs_path

app/views/players/index.html.haml
.sports-wrapper.row
  %h1 #{@club.name} Players

  %p
    = link_to "Add New Player", new_sport_club_player_path

  -@club.players.each do |player|
    .sport
      .sport-head
        .name #{player.name}
      .image.center-block
        = image_tag(player.image_link, style: "max-width: 640px", class: 'img-responsive')
      %p.caption #{player.position} (#{player.country})
      %p.caption #{player.description}
      .text-center.edit-links
        = link_to "show", sport_club_player_path(@club.sport.id, @club.id, player)
        |
        = link_to "edit", edit_sport_club_player_path(@club.sport.id, @club.id, player)
        |
        = link_to "delete", sport_club_player_path(@club.sport.id, @club.id, player), method: :delete, data: {confirm: "Are you sure?"}

/ name
/ position
/ country
/ image_link
/ description

app/views/players/new.html.haml
.sports-wrapper.row
  %h1
    New Player

  = render 'form'

  %p
    = link_to "Back", sport_club_players_path(@sport, @club)

app/views/players/search.html.haml
.sports-wrapper.row
  %h1 Result for: `#{@query}`

  -@results.each do |player|
    .sport
      .sport-head
        .name #{player.name}
      .image.center-block
        = link_to image_tag(player.image_link, style: "max-width: 640px"), sport_club_player_path(player.club.sport.id, player.club.id, player), class: 'img-responsive'
      %p.caption #{player.position} (#{player.country})
      %p.caption #{player.description}

/ name
/ position
/ country
/ image_link
/ description

app/views/players/show.html.haml
.sports-wrapper.row
  %p
    %strong Player:
    ="#{@player.name}"
  %p
    %strong Country:
    ="#{@player.country}"
  %p
    %strong Position:
    ="#{@player.position}"

  %img{ src: "#{@player.image_link}", title: @player.description, style: "max-width: 640px" }

  %p.caption
    ="#{@player.description}"

  .text-center.edit-links
    = link_to "Back", sport_club_players_path(@player.club.sport, @player.club)

app/views/sports/index.html.haml
.sports-wrapper.row
  %h1
    Sports Categories

  %p
    = link_to "New Sports", new_sport_path
  -@sports.each do |sport|
    .sport
      .sport-head
        .name #{sport.title}
      .image.center-block
        = link_to image_tag(sport.image_link, style: "max-width: 640px"), sport_clubs_path(sport), class: 'img-responsive'
      %p.caption #{sport.description}
      .text-center.edit-links
        = link_to "show", sport_path(sport)
        |
        = link_to "edit", edit_sport_path(sport)
        |
        = link_to "delete", sport_path(sport), method: :delete, data: {confirm: "Are you sure?"}

app/views/sports/show.html.haml
.sports-wrapper.row
  %p
    %strong Sport:
    ="#{@sport.title}"

  %img{ src: "#{@sport.image_link}", title: @sport.description, style: "max-width: 640px" }

  %p.caption
    ="#{@sport.description}"

  .text-center.edit-links
    = link_to "Back", sports_path